name: Report an issue with ESPHome
description: Create a report to help ESPHome improve.
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        If you have a feature or enhancement request, please use the [feature request][fr] repository.

        [fr]: https://github.com/esphome/feature-requests/issues/new?assignees=&labels=&template=feature_request.md
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Which version of ESPHome has the issue?
      description: >
        ESPHome version like v1.19.0 or v1.XX-dev.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you using?
      options:
        - Home Assistant Add-on
        - Docker
        - pip
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What platform are you using?
      options:
        - ESP8266
        - ESP32
  - type: input
    attributes:
      label: Board
      description: >
        The name of the board you are using. For example, sonoff basic, nodemcu, shelly.

  - type: input
    id: component_name
    attributes:
      label: Component causing the issue
      description: >
        The name of the component or platform. For example, api/i2c or ultrasonic.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Example YAML snippet
      description: |
        If this issue has an example piece of YAML that can help reproducing this problem, please provide.
      render: yaml
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
